server:
  port: 9099
spring:
  application:
    name: rag-mcp-server
mcp:
  mysql:
    host: 127.0.0.1
    port: 3306
    database: testdatabase
    username: root
    password: 123456
    allowedTables:
      - tableName: users
        description: 用户信息表
        maxRows: 50
      - tableName: orders
        description: 订单表